package vagrant

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/TomHoenderdos/vbox/internal/config"
	"github.com/TomHoenderdos/vbox/internal/profile"
)

type vagrantfileData struct {
	Memory    int
	CPUs      int
	NeedsUSB  bool
	Ports     []config.Port
	Provision string
}

const vagrantfileTmpl = `# -*- mode: ruby -*-
# vi: set ft=ruby :
# Generated by vbox — do not edit manually

Vagrant.configure("2") do |config|
  config.vm.box = "luminositylabsllc/bento-ubuntu-24.04-arm64"

  # Enable SSH agent forwarding so git push works from the VM
  config.ssh.forward_agent = true

  config.vm.provider "parallels" do |prl|
    prl.memory = {{.Memory}}
    prl.cpus = {{.CPUs}}
{{- if .NeedsUSB}}
    prl.customize "post-import", ["set", :id, "--device-add", "usb"]
{{- end}}
  end
{{range .Ports}}
  config.vm.network "forwarded_port", guest: {{.Guest}}, host: {{.Host}}, auto_correct: true  # {{.Label}}
{{- end}}

  # Bidirectional shared folder via Parallels (real-time sync both ways)
  config.vm.synced_folder ".", "/vagrant"

  # Sync Claude Code config and credentials from host
  config.vm.synced_folder "#{Dir.home}/.claude", "/home/vagrant/.claude", type: "rsync"
  config.vm.provision "file", source: "#{Dir.home}/.claude.json", destination: "/home/vagrant/.claude.json"

  # Sync tool credentials (GitHub CLI, etc.) if they exist
  if Dir.exist?(File.join(Dir.home, ".config", "gh"))
    config.vm.synced_folder "#{Dir.home}/.config/gh", "/home/vagrant/.config/gh", type: "rsync"
  end

  config.vm.provision "shell", inline: <<-SHELL
{{.Provision}}    echo "vbox provisioning complete!"
  SHELL
end
`

// GenerateVagrantfile creates a Vagrantfile from config and profile data.
func GenerateVagrantfile(dir string, cfg *config.Config) error {
	// Collect provision scripts from base + selected profiles
	profiles := append([]string{"base"}, cfg.Profiles...)
	var provisions []string
	for _, name := range profiles {
		if !profile.Exists(name) {
			fmt.Fprintf(os.Stderr, "Warning: profile '%s' not found, skipping\n", name)
			continue
		}
		prov, err := profile.GetProvision(name, dir)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: profile '%s' provision failed: %v\n", name, err)
			continue
		}
		provisions = append(provisions, prov)
	}

	// Check USB needs
	needsUSB := false
	for _, name := range cfg.Profiles {
		usb, _ := profile.GetUSB(name)
		if usb {
			needsUSB = true
			break
		}
	}

	data := vagrantfileData{
		Memory:    cfg.Memory,
		CPUs:      cfg.CPUs,
		NeedsUSB:  needsUSB,
		Ports:     cfg.Ports,
		Provision: strings.Join(provisions, "\n"),
	}

	tmpl, err := template.New("Vagrantfile").Parse(vagrantfileTmpl)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	f, err := os.Create(filepath.Join(dir, "Vagrantfile"))
	if err != nil {
		return err
	}
	defer f.Close()

	if err := tmpl.Execute(f, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	fmt.Println("==> Vagrantfile generated")
	return nil
}
