# -*- mode: ruby -*-
# vi: set ft=ruby :
# Generated by vbox — do not edit manually

Vagrant.configure("2") do |config|
  config.vm.box = "luminositylabsllc/bento-ubuntu-24.04-arm64"

  config.vm.provider "parallels" do |prl|
    prl.memory = 2048
    prl.cpus = 2

  end

  config.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true  # Go HTTP

  config.vm.synced_folder ".", "/vagrant", type: "rsync",
    rsync__exclude: [".git/", ".vagrant/", "_build/", "deps/", "node_modules/"]

  # Sync Claude Code config and credentials from host
  config.vm.synced_folder "#{Dir.home}/.claude", "/home/vagrant/.claude", type: "rsync"
  config.vm.provision "file", source: "#{Dir.home}/.claude.json", destination: "/home/vagrant/.claude.json"

  # Sync Codex CLI config and credentials from host if they exist
  if Dir.exist?(File.join(Dir.home, ".codex"))
    config.vm.synced_folder "#{Dir.home}/.codex", "/home/vagrant/.codex", type: "rsync"
  end

  # Sync tool credentials (GitHub CLI, etc.) if they exist
  if Dir.exist?(File.join(Dir.home, ".config", "gh"))
    config.vm.synced_folder "#{Dir.home}/.config/gh", "/home/vagrant/.config/gh", type: "rsync"
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y wget gnupg2 git curl unzip build-essential python3 npm

    # Install ASDF version manager (skip if already installed)
    if [ ! -d /home/vagrant/.asdf ]; then
      su - vagrant -c 'git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.14.0'
    fi

    # Remove npm-installed claude if present (conflicts with native, blocks auto-update)
    npm uninstall -g @anthropic-ai/claude-code 2>/dev/null || true

    # Install Claude Code (native) — must run as vagrant user for correct ownership
    su - vagrant -c '
      mkdir -p ~/.local/bin
      curl -fsSL https://claude.ai/install.sh | bash
    '

    # Install Codex CLI
    npm install -g @openai/codex --no-audit

    # Ensure ~/.local is fully owned by vagrant (native install needs write access for auto-updates)
    chown -R vagrant:vagrant /home/vagrant/.local

    # Install GitHub CLI
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" > /etc/apt/sources.list.d/github-cli.list
    apt-get update
    apt-get install -y gh

    # Trust GitHub SSH host key
    su - vagrant -c 'mkdir -p ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts 2>/dev/null'

    # Configure environment for all shell types (interactive, non-interactive, login)
    # /etc/profile.d/ is sourced by login shells; we also add to .bashrc for interactive use
    cat > /etc/profile.d/vbox-asdf.sh << 'ASDFPROFILE'
export ASDF_DIR="$HOME/.asdf"
if [ -d "$ASDF_DIR" ]; then
  . "$ASDF_DIR/asdf.sh"
fi
ASDFPROFILE

    cat > /etc/profile.d/vbox-path.sh << 'PATHPROFILE'
export PATH="$HOME/.local/bin:$PATH"
PATHPROFILE

    # Also add to .bashrc for interactive shells (completions, alias, cd)
    BASHRC="/home/vagrant/.bashrc"
    grep -qF '.asdf/asdf.sh' "$BASHRC" || su - vagrant -c 'echo ". $HOME/.asdf/asdf.sh" >> ~/.bashrc'
    grep -qF '.asdf/completions' "$BASHRC" || su - vagrant -c 'echo ". $HOME/.asdf/completions/asdf.bash" >> ~/.bashrc'
    grep -qF '.local/bin' "$BASHRC" || echo 'export PATH="$HOME/.local/bin:$PATH"' >> "$BASHRC"
    grep -qF 'cd /vagrant' "$BASHRC" || echo 'cd /vagrant' >> "$BASHRC"
    grep -qF 'alias claude=' "$BASHRC" || echo 'alias claude="claude --dangerously-skip-permissions"' >> "$BASHRC"

    # Add to .profile so non-interactive SSH commands (used by Claude Code) can find tools
    PROFILE="/home/vagrant/.profile"
    grep -qF '.asdf/asdf.sh' "$PROFILE" || su - vagrant -c 'echo ". \$HOME/.asdf/asdf.sh" >> ~/.profile'
    grep -qF '.local/bin' "$PROFILE" || su - vagrant -c 'echo "export PATH=\$HOME/.local/bin:\$PATH" >> ~/.profile'

    # Claude Code: merge vbox defaults into existing settings (synced from host)
    mkdir -p /home/vagrant/.claude
    CLAUDE_SETTINGS="/home/vagrant/.claude/settings.json"
    python3 -c "
import json, os
path = '$CLAUDE_SETTINGS'
settings = {}
if os.path.exists(path):
    with open(path) as f:
        settings = json.load(f)
settings['skipDangerousModePermissionPrompt'] = True
dirs = settings.get('trustedDirectories', [])
if '/vagrant' not in dirs:
    dirs.append('/vagrant')
settings['trustedDirectories'] = dirs
settings.pop('enabledPlugins', None)
with open(path, 'w') as f:
    json.dump(settings, f, indent=2)
"
    chown -R vagrant:vagrant /home/vagrant/.claude
    su - vagrant -c 'source ~/.asdf/asdf.sh && asdf plugin add golang'
    su - vagrant -c 'source ~/.asdf/asdf.sh && asdf install golang 1.24.1'
    su - vagrant -c 'source ~/.asdf/asdf.sh && asdf global golang 1.24.1'

    echo "vbox provisioning complete!"
  SHELL
end
